In [2]:
import sqlite3
import pandas as pd

In [12]:
con = sqlite3.connect("data/receiving_data.db")
cur = con.cursor()

After connecting to the receiving_data.db, I query all receiving data from both tables by the Wide Receiver position and then close the connection to the SQL db.

In [17]:
NFL_wr = pd.read_sql_query("SELECT * from NFL where position == 'WR'", con)
NCAA_wr = pd.read_sql_query("SELECT * from NCAA where position == 'WR'", con)

con.close()

In [15]:
NFL_sql.head()

,index,year,player,player_id,position,team_name,player_game_count,avg_depth_of_target,avoided_tackles,caught_percent,...,targeted_qb_rating,targets,touchdowns,wide_rate,wide_snaps,yards,yards_after_catch,yards_after_catch_per_reception,yards_per_reception,yprr
0,0,2015,Antonio Brown,5718,WR,PIT,17,11.2,25,70.8,...,99.3,202,10,79.3,581,1953,699,4.9,13.7,2.91
1,1,2015,DeAndre Hopkins,7808,WR,HST,17,14.6,5,59.1,...,90.7,198,11,84.7,626,1590,233,2.0,13.6,2.27
2,2,2015,Julio Jones,6158,WR,ATL,16,10.5,20,70.5,...,110.7,193,8,71.3,469,1871,665,4.9,13.8,3.04
3,3,2015,Demaryius Thomas,5547,WR,DEN,19,10.6,20,59.3,...,76.7,189,6,77.1,551,1364,515,4.6,12.2,2.01
4,4,2015,Brandon Marshall,3064,WR,NYJ,16,12.7,14,65.3,...,99.4,167,14,77.3,514,1502,439,4.0,13.8,2.35